# Generated by Django 5.0.4 on 2024-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
