# Generated by Django 5.0.4 on 2024-05-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_task_date_end_task_date_start_task_user_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='Document',
        ),
    ]
