# Generated by Django 5.0.4 on 2024-05-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_alter_user_options_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
