# Generated by Django 5.0.4 on 2024-05-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_remove_user_name_remove_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image_path',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='worker', max_length=20),
        ),
    ]
